name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: turtlesec-no/get-ninja@main
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        sdk: 10.0.22621.0
        toolset: 14.29.30153
    - name: generate-makefiles
      shell: bash
      run: |
        curl -Lo https://github.com/aseprite/skia/releases/latest/Skia-Windows-Release-x64.zip
        7z x Skia-Windows-Release-x64.zip -o ./skia
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_UI=on \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=./skia \
          -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \
          -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib
    - name: compile
      shell: bash
      run: |
        cd build && ninja
    - uses: actions/upload-artifact@v4
      with:
        name: aseprite
        path: |
          D:/a/aseprite/aseprite/build/bin/data
          D:/a/aseprite/aseprite/build/bin/aseprite.exe
